---
# Dependencies role tasks
- name: Ensure Homebrew is installed (macOS only)
  block:
    - name: Check if Homebrew is installed
      stat:
        path: /usr/local/bin/brew
      register: brew_installed
      when: os_family == "Darwin"

    - name: Install Homebrew
      shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /usr/local/bin/brew
      when: os_family == "Darwin" and not has_brew and not brew_installed.stat.exists
  rescue:
    - name: Display Homebrew installation failure
      debug:
        msg: "Failed to install Homebrew. Please check the error message above and try installing Homebrew manually."
  tags: brew

- name: Handle apt packages (Ubuntu/Debian)
  block:
    - name: Update package repositories
      become: true
      apt:
        update_cache: yes
      when: has_apt
      register: apt_update

    - name: Upgrade all packages
      become: true
      apt:
        upgrade: full
      when: has_apt
      register: apt_upgrade

    - name: Install common packages
      become: true
      package:
        name: "{{ common_packages }}"
        state: present
      register: common_install

    - name: Install extra packages
      become: true
      package:
        name: "{{ extra_packages }}"
        state: present
      register: extra_install
  rescue:
    - name: Display package installation failure
      debug:
        msg: "Failed to install some packages. Please check the error message above and try installing them manually."
  when: has_apt
  tags: system_packages

- name: Handle brew packages (macOS)
  block:
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes
      when: has_brew

    - name: Install common packages with Homebrew
      homebrew:
        name: "{{ common_packages }}"
        state: present
      when: has_brew

    - name: Install extra packages with Homebrew
      homebrew:
        name: "{{ extra_packages }}"
        state: present
      when: has_brew
  rescue:
    - name: Display package installation failure
      debug:
        msg: "Failed to install some packages. Please check the error message above and try installing them manually."
  when: has_brew
  tags: system_packages
