services:
  dev-env:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: dev-container:latest
    container_name: dev-environment
    hostname: dev-container

    # Port mapping for development servers
    ports:
      - "18080-18090:18080-18090"  # Development server port range

    # Volume mounts
    volumes:
      # Mount your Projects directory (adjust path as needed)
      - "${PROJECTS_DIR:-$HOME/Projects}:/home/dev/Projects"
      # Optional: persist home directory customizations
      - dev_home:/home/dev/.config

    # Environment variables (reads from .env.local or .env file if needed)
    environment:
      - TZ=${TZ:-UTC}

    # Security settings
    security_opt:
      - no-new-privileges:false

    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

    # Restart policy for long-running container
    restart: unless-stopped

    # Health check for container readiness
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/.container-ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# Named volumes for persistence
volumes:
  dev_home:
    name: dev_home_config
